# Generated by Django 4.1.7 on 2023-03-09 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maps_text', models.CharField(max_length=50)),
                ('difficulty', models.IntegerField(default=1)),
                ('accesses', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Mapa',
            },
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Escolha'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Questão', 'verbose_name_plural': 'Questões'},
        ),
        migrations.AddField(
            model_name='question',
            name='maps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.maps'),
        ),
    ]
